apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: application
spec:
  vars:
    computed:
      - name: helmConfig
        code: |
          {
            command: './helm-start.sh'
          }
  dataSources:
    - exec://helm-source?configVar=helmConfig
  environments:
    dev:
      server: https://127.0.0.1:6443
      defaultNamespace: postgres
